version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-api
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    environment:
      - AWS_REGION=sa-east-1
    networks:
      - url-shortener-network
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    container_name: url-shortener-localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
    networks:
      - url-shortener-network

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: url-shortener-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    networks:
      - url-shortener-network
    depends_on:
      - localstack

networks:
  url-shortener-network:
    driver: bridge
